// Code generated by protoc-gen-gogo.
// source: cmd.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	cmd.proto
	cmds.proto

It has these top-level messages:
	Cmd
*/
package msg

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Cmd_Cmd int32

const (
	Cmd_CMD_CLOSE Cmd_Cmd = 0
	Cmd_CMD_RAW   Cmd_Cmd = 1
	Cmd_CMD_PWR   Cmd_Cmd = 2
	Cmd_CMD_VOL   Cmd_Cmd = 3
)

var Cmd_Cmd_name = map[int32]string{
	0: "CMD_CLOSE",
	1: "CMD_RAW",
	2: "CMD_PWR",
	3: "CMD_VOL",
}
var Cmd_Cmd_value = map[string]int32{
	"CMD_CLOSE": 0,
	"CMD_RAW":   1,
	"CMD_PWR":   2,
	"CMD_VOL":   3,
}

func (x Cmd_Cmd) Enum() *Cmd_Cmd {
	p := new(Cmd_Cmd)
	*p = x
	return p
}
func (x Cmd_Cmd) String() string {
	return proto.EnumName(Cmd_Cmd_name, int32(x))
}
func (x *Cmd_Cmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Cmd_Cmd_value, data, "Cmd_Cmd")
	if err != nil {
		return err
	}
	*x = Cmd_Cmd(value)
	return nil
}

type Cmd_PwrValue int32

const (
	Cmd_PWR_OFF Cmd_PwrValue = 1
	Cmd_PWR_ON  Cmd_PwrValue = 2
)

var Cmd_PwrValue_name = map[int32]string{
	1: "PWR_OFF",
	2: "PWR_ON",
}
var Cmd_PwrValue_value = map[string]int32{
	"PWR_OFF": 1,
	"PWR_ON":  2,
}

func (x Cmd_PwrValue) Enum() *Cmd_PwrValue {
	p := new(Cmd_PwrValue)
	*p = x
	return p
}
func (x Cmd_PwrValue) String() string {
	return proto.EnumName(Cmd_PwrValue_name, int32(x))
}
func (x *Cmd_PwrValue) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Cmd_PwrValue_value, data, "Cmd_PwrValue")
	if err != nil {
		return err
	}
	*x = Cmd_PwrValue(value)
	return nil
}

type Cmd_VolValue int32

const (
	Cmd_VOL_UP        Cmd_VolValue = 1
	Cmd_VOL_DOWN      Cmd_VolValue = 2
	Cmd_VOL_UP_FAST   Cmd_VolValue = 3
	Cmd_VOL_DOWN_FAST Cmd_VolValue = 4
)

var Cmd_VolValue_name = map[int32]string{
	1: "VOL_UP",
	2: "VOL_DOWN",
	3: "VOL_UP_FAST",
	4: "VOL_DOWN_FAST",
}
var Cmd_VolValue_value = map[string]int32{
	"VOL_UP":        1,
	"VOL_DOWN":      2,
	"VOL_UP_FAST":   3,
	"VOL_DOWN_FAST": 4,
}

func (x Cmd_VolValue) Enum() *Cmd_VolValue {
	p := new(Cmd_VolValue)
	*p = x
	return p
}
func (x Cmd_VolValue) String() string {
	return proto.EnumName(Cmd_VolValue_name, int32(x))
}
func (x *Cmd_VolValue) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Cmd_VolValue_value, data, "Cmd_VolValue")
	if err != nil {
		return err
	}
	*x = Cmd_VolValue(value)
	return nil
}

type Cmd struct {
	Cmd              *Cmd_Cmd      `protobuf:"varint,1,req,name=cmd,enum=msg.Cmd_Cmd" json:"cmd,omitempty"`
	IntValue         *int32        `protobuf:"varint,2,opt,name=intValue" json:"intValue,omitempty"`
	StrValue         *string       `protobuf:"bytes,3,opt,name=strValue" json:"strValue,omitempty"`
	Pwr              *Cmd_PwrValue `protobuf:"varint,4,opt,name=pwr,enum=msg.Cmd_PwrValue" json:"pwr,omitempty"`
	Vol              *Cmd_VolValue `protobuf:"varint,5,opt,name=vol,enum=msg.Cmd_VolValue" json:"vol,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}

func (m *Cmd) GetCmd() Cmd_Cmd {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return Cmd_CMD_CLOSE
}

func (m *Cmd) GetIntValue() int32 {
	if m != nil && m.IntValue != nil {
		return *m.IntValue
	}
	return 0
}

func (m *Cmd) GetStrValue() string {
	if m != nil && m.StrValue != nil {
		return *m.StrValue
	}
	return ""
}

func (m *Cmd) GetPwr() Cmd_PwrValue {
	if m != nil && m.Pwr != nil {
		return *m.Pwr
	}
	return Cmd_PWR_OFF
}

func (m *Cmd) GetVol() Cmd_VolValue {
	if m != nil && m.Vol != nil {
		return *m.Vol
	}
	return Cmd_VOL_UP
}

func init() {
	proto.RegisterEnum("msg.Cmd_Cmd", Cmd_Cmd_name, Cmd_Cmd_value)
	proto.RegisterEnum("msg.Cmd_PwrValue", Cmd_PwrValue_name, Cmd_PwrValue_value)
	proto.RegisterEnum("msg.Cmd_VolValue", Cmd_VolValue_name, Cmd_VolValue_value)
}
